[[dploy]]
== dploy: Build and Deploy Your Java Application

:repo-raw-urlprefix: https://bitbucket.org/artofcoding/eu.artofcoding.rootaid/raw
:dploy-conf-template: `dploy.<projectname>.conf`

=== What Is dploy?

`dploy` is a little tool to ease shipping applications through source code management. It consists of some little concepts and a shell script which uses your Maven based build, executes it, finds deployable artifacts and collects them.

=== What Do I Need?

You need:

. A https://maven.apache.org[Maven] based build
. git Source Code Repository
.. Access to it from deployment host, see <<ssh-deployment-key,SSH deployment key>>
. Debian/Ubuntu Linux
.. Installed software, see <<setup-dploy>>

[[building-and-deploying-a-project-with-dploy]]
=== Building and Deploying a Project With dploy

TIP: Optional task, create a dedicated directory for your applications.

On your Linux machine create a directory for your applications, where {dploy-conf-template} files are located and `dploy` can do its work:

.Preparation
[source,bash,lineno]
----
cd $HOME
mkdir app
cd app
----

[[project-configuration]]
==== Project Configuration

For every project you need a configuration file, {dploy-conf-template}, where `projectname` is the name of project's source code repository.

.dploy.foo.conf
[source,bash,lineno]
----
# Project repository
PROJECT_REPO_HOST="bitbucket.org"
PROJECT_REPO_USER="artofcoding"
----

See {repo-raw-urlprefix}/share/dploy.example.conf[`dploy.example.conf`] for more options.

[[setup-dploy]]
==== Setup dploy

NOTE: You can also skip this and install software on your own.

Before first usage of `dploy` you need to perform a setup routine, which installs needed software:

* ssh
* unzip
* git
* Java
* Maven

.Initialize dploy and install needed software
[source,bash,lineno]
----
dploy -p foo -i setup-linux
----

[[ssh-deployment-key]]
==== SSH Deployment Key

Generate a deployment key for your project and submit the resulting public key to owner of repository.

[source,bash,lineno]
----
dploy -p foo -i ssh-deployment-key
----

`dploy` will show generated SSH public key at the end. In case you need to look it up yourself, it is put in `$HOME/.ssh`:

[source,bash,lineno]
----
cat $HOME/id_rsa_dploy.pub
----

For setting this up in your git repository:

* See https://confluence.atlassian.com/bitbucket/use-deployment-keys-294486051.html[Bitbucket: Deployment Keys]
* See https://github.com[github.com], open a project, go to Settings > Deploy Keys

==== sudo

.Setup sudo
[source,bash,lineno]
----
dploy -p foo -i sudo
----

=== Build Your Project

==== Review Build

[source,bash,lineno]
----
dploy -p foo -b default -t review
----

==== Production Build

[source,bash,lineno]
----
dploy -p foo -b release/1.1 -t production
----
