== Synchronize data

=== iRedMail Anti Spam

==== Whitelists

* Dump table `cluebringer.policy_group_members`, field `member` where `policygroupid == 3`
** `SELECT member FROM cluebringer.policy_group_members WHERE policygroupid = 3`
* Copy to iRedAdmin menu:System[Anti Spam > Whitelists and Blacklists]
** Text box under menu:For Inbound Emails[Whitelisted Senders]

This feature requires iRedAPD plugin 'amavisd_wblist', please make sure it's enabled in file `/opt/iredapd/settings.py`.

=== DKIM

[source,bash,linenums]
.Copy DKIM signatures
----
rsync -av -e ssh dkim/ mx-netcup.rootaid.de::dkim
----

[source,bash,linenums]
.Add DKIM signatures in /etc/amavis/conf.d/50-user
----
# Add dkim_key here.
dkim_key("0xcafebabe.eu", "dkim", "/var/lib/dkim/0xcafebabe.eu.pem");
----

WARNING: Take care!

  # Note that signing mail for subdomains with a key of a parent
  # domain is treated by recipients as a third-party key, which
  # may 'hold less merit' in their eyes. If one has a choice,
  # it is better to publish a key for each domain (e.g. host1.a.cn)
  # if mail is really coming from it. Sharing a pem file
  # for multiple domains may be acceptable, so you don't need
  # to generate a different key for each subdomain, but you
  # do need to publish it in each subdomain. It is probably
  # easier to avoid sending addresses like host1.a.cn and
  # always use a parent domain (a.cn) in 'From:', thus
  # avoiding the issue altogether.
  #dkim_key("host1.0xcafebabe.eu", "dkim", "/var/lib/dkim/0xcafebabe.eu.pem");
  #dkim_key("host3.0xcafebabe.eu", "dkim", "/var/lib/dkim/0xcafebabe.eu.pem");

=== Roundcube

Copy MySQL tables `roundcube.users` and `roundcube.identities` to new server.

=== User's emails

Setup `rsync` by creating a `rsyncd.conf` and starting it when a user logs in via `ssh` in `.ssh/authorized_keys`.

[source,bash,linenums]
./root/iredmail-rsyncd.conf on new server
----
uid = nobody
gid = nobody
use chroot = yes
max connections = 4
syslog facility = local5
pid file = /root/iredmail-rsyncd.pid

[root]
  path = /root
  read only = false
  uid = root
  gid = root
  hosts allow = <enter ip of old mx here>

[vmail1]
  path = /var/vmail/vmail1
  read only = false
  uid = vmail
  gid = vmail
  hosts allow = <enter ip of old mx here>

[dkim]
  path = /var/lib/dkim
  read only = false
  uid = vmail
  gid = vmail
  hosts allow = <enter ip of old mx here>
----

[source,bash,linenums]
./root/.ssh/authorized_keys
----
command="rsync --config=/root/iredmail-rsyncd.conf --server --daemon" ssh-rsa AAAAB3Nza..== root@old-mx
----

Use `cron` to synchronize regularly:

[source,bash,linenums]
.crontab
----
#    m     h    dom mon dow usercommand
0-59/5     *    *   *   *   /root/bin/iredmail-sync
----
