[Backup & Recovery]
== Backup & Recovery

=== Concept

I defined the following 4 backup sets:

. The Linux system
.. Backup set "system"
. Root's data
.. Backup set "root"
. iRedMail configuration
.. Backup set "iredmail"
. iRedMail data
.. Backup set "iredmail-vmail"

These backup sets are created and maintained through `duply`,
an easy to use command line interface for `duplicity`.
Alternatives to duply can be found http://duply.net/#Alternatives[here].

Backups are put on a NFS share provided by our provider, see <<NFS Storage>>.

Every sunday a full backup of all backup sets is created and
at every day of week a incremental backup is made.

=== Recovery

Recovery procedure:

. Setup Linux system (as described in <<Setup Linux>>)
. Install iRedMail software (as described in <<Setup iRedMail>> and <<Setup iRedAdmin>>)
. Recover iRedMail configuration
. Recover iRedMail data (user's emails)

For performing backup & recovery tasks see <<Backup Maintenance>>.

=== Install Software

Install duply and duplicity:

[source,bash,linenums]
----
apt-get install -y duplicity duply
----

==== Setup GnuPG Key

[source,bash,linenums]
.Generate GnuPG key
----
gpg --gen-key
----

[source,bash,linenums]
.Key generation on mx.1ci.net
----
root@mx:~# gpg --gen-key

[...]

gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
Please select what kind of key you want:
   (1) RSA and RSA (default)
   (2) DSA and Elgamal
   (3) DSA (sign only)
   (4) RSA (sign only)
Your selection? 1
RSA keys may be between 1024 and 4096 bits long.
What keysize do you want? (2048)
Requested keysize is 2048 bits
Please specify how long the key should be valid.
         0 = key does not expire
      <n>  = key expires in n days
      <n>w = key expires in n weeks
      <n>m = key expires in n months
      <n>y = key expires in n years
Key is valid for? (0)
Key does not expire at all

[...]

Real name: Mail Exchanger
Email address: root@mx.1ci.net
Comment: System Account
You selected this USER-ID:
    "Mail Exchanger (System Account) <root@mx.1ci.net>"

[...]

gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 7FDE5BBF marked as ultimately trusted
public and secret key created and signed.

gpg: checking the trustdb
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
pub   2048R/7FDE5BBF 2016-03-22
      Key fingerprint = DB0F 7E1A B65F 3E96 03EF  1E32 3984 AFB8 7FDE 5BBF
uid                  Mail Exchanger (System Account) <root@mx.1ci.net>
sub   2048R/5A11A14F 2016-03-22
----

[NFS Storage]
==== NFS Storage

Mount external NFS storage for backup.

[source,bash,linenums]
.Do this once for setting up NFS storage
----
mkdir /mnt/backup
echo -e "46.38.248.197:/vol-78701-1  /mnt/backup  nfs  rw,rsize=1048576,wsize=1048576  0  0" >>/etc/fstab
mount /mnt/backup
----

==== duply Configurations

===== system

[source,bash,linenums]
.Create duply configuration
----
duply system create
----

[source,bash,linenums]
.Changes to /root/.duply/system/conf
----
root@mx:~# grep -e ^"[^#]" /root/.duply/system/conf
GPG_KEY='7FDE5BBF'
GPG_PW='Tecoh4yai9eaJicu'
TARGET='file:///mnt/backup/mx.1ci.net/system'
SOURCE='/'
MAX_AGE=1M
MAX_FULL_BACKUPS=1
MAX_FULLS_WITH_INCRS=1
MAX_FULLBKP_AGE=1M
----

[source,bash,linenums]
.Includes and excludes defined in /root/.duply/system/exclude
----
# Linux
- /proc/**
- /dev/**
- /lost+found/**
- /tmp/**
- /media/**
- /mnt/**
- /root/.cache/**
- /root/.gnupg/**
- /var/cache/**

# iRedMail
- /opt/**
- /usr/share/apache2/ired*
- /usr/share/apache2/iRed*
- /var/vmail/**
----

===== root

[source,bash,linenums]
.Create duply configuration
----
duply root create
----

[source,bash,linenums]
.Changes to /root/.duply/root/conf
----
root@mx:~# grep -e ^"[^#]" /root/.duply/root/conf
GPG_KEY='7FDE5BBF'
GPG_PW='Tecoh4yai9eaJicu'
TARGET='file:///mnt/backup/mx.1ci.net/root'
SOURCE='/root'
MAX_AGE=1W
MAX_FULL_BACKUPS=1
MAX_FULLS_WITH_INCRS=1
MAX_FULLBKP_AGE=1W
----

[source,bash,linenums]
.Includes and excludes defined in /root/.duply/root/exclude
----
- /root/.cache/**
- /root/.gnupg/**
----

===== iredmail

[source,bash,linenums]
.Create duply configuration
----
duply iredmail create
----

[source,bash,linenums]
.Changes to /root/.duply/iredmail/conf
----
root@mx:~# grep -e ^"[^#]" /root/.duply/iredmail/conf
GPG_KEY='7FDE5BBF'
GPG_PW='Tecoh4yai9eaJicu'
TARGET='file:///mnt/backup/mx.1ci.net/iredmail'
SOURCE='/'
MAX_AGE=1M
MAX_FULL_BACKUPS=1
MAX_FULLS_WITH_INCRS=1
MAX_FULLBKP_AGE=1M
----

[source,bash,linenums]
.Includes and excludes defined in /root/.duply/iredmail/exclude
----
# Linux
+ /etc/systemd
+ /etc/hosts
+ /etc/hostname
+ /etc/mailname
+ /etc/passwd
+ /etc/group
+ /etc/default
+ /etc/cron*
+ /etc/network

# Security
+ /etc/ssh
+ /etc/ssl
+ /etc/fail2ban

# LAMP
+ /etc/mysql
+ /etc/apache2
+ /etc/php5

# iRedMail
+ /etc/iredmail-release
+ /etc/ldap*
+ /etc/postfix
+ /etc/spamassassin
+ /etc/amavis
+ /etc/dovecot
+ /etc/sogo

+ /opt/ired*
+ /opt/iRed*
+ /opt/www/ired*
+ /opt/www/iRed*
+ /opt/www/roundcube*

# Exclude rest
- /**
----

===== iredmail-vmail

[source,bash,linenums]
.Create duply configuration
----
duply iredmail-vmail create
----

[source,bash,linenums]
.Changes to /root/.duply/iredmail-vmail/conf
----
root@mx:~# grep -e ^"[^#]" /root/.duply/iredmail-vmail/conf
GPG_KEY='7FDE5BBF'
GPG_PW='Tecoh4yai9eaJicu'
TARGET='file:///mnt/backup/iredmail-vmail'
SOURCE='/var/vmail'
----

==== References

* http://duply.net
* https://www.thomas-krenn.com/de/wiki/Backup_unter_Linux_mit_duply
* https://www.howtoforge.de/anleitung/verschlusselte-ftp-backups-mit-duplicity-und-duply-erstellen-debian-squeeze/
* https://wiki.archlinux.org/index.php/Duply
