=== SMTP Server Postfix

==== Message Limits

[source,bash,linenums]
.Set message limits in /etc/postfix/main.cf
----
postconf -e mailbox_size_limit=104857600
postconf -e message_size_limit=104857600
----

==== Aliases

[source,bash,linenums]
./etc/postfix/aliases
----
# /etc/aliases
mailer-daemon: postmaster
postmaster: root
#nobody: root
hostmaster: root
usenet: root
news: root
webmaster: root
www: root
ftp: root
abuse: root
noc: root
security: root
www-data: root
nobody: root
vmail: root
root: postmaster@0xcafebabe.eu
clamav: root
amavis: root
virusalert: root
iredapd: root
sogo: root
----

[source,bash,linenums]
.Rebuild alias database
----
postalias /etc/postfix/aliases
----

[source,bash,linenums]
.Query alias database
----
postalias -q root /etc/postfix/aliases
----

==== Client Access

_Add_ the following configuration for client access:

[source,bash.linenums]
./etc/postfix/main.cf
----
# Client restriction
smtpd_client_restrictions =
    check_client_access pcre:/etc/postfix/client_access.pcre
----

[source,bash,linenums]
.Check client access
----
postmap -q 1.2.3.4 pcre:/etc/postfix/client_access.pcre
----

==== Sender Access

This will enable local email relaying without authentication.
The rule `check_sender_access` was moved above `reject_sender_login_mismatch`
to allow senders by domain or email address solely.

WARNING: This will result in higher spam amount to process as spammers
         use a local domain to send spam.

[source,bash,linenums]
.Sender access in /etc/postfix/main.cf
----
# Sender restrictions
smtpd_sender_restrictions =
    reject_unknown_sender_domain
    reject_non_fqdn_sender
    reject_unlisted_sender
    permit_mynetworks
    check_sender_access pcre:/etc/postfix/sender_access.pcre
    reject_sender_login_mismatch
    permit_sasl_authenticated
----

[source,bash,linenums]
.List senders domain or email address in /etc/postfix/sender_access.pcre
----
root@mx:/etc/postfix# cat sender_access.pcre
# Test
/0xcafebabe\.eu/		OK
# BBORS
/bbors-kreuznacht\.de/		OK
# Herwe
/info@herwe\.de/		OK
/bestellung@cucubas\.de/	OK
----

[source,bash,linenums]
.Check sender access
----
postmap -q ralf@0xcafebabe.eu pcre:/etc/postfix/sender_access.pcre
----

==== SSL/TLS

[source,bash,linenums]
.Setup SSL Certificate in /etc/postfix/main.cf
----
smtpd_tls_security_level = may
smtpd_tls_loglevel = 0
smtpd_tls_key_file = /etc/ssl/private/mx.1ci.net.key
smtpd_tls_cert_file = /etc/ssl/certs/mx.1ci.net.crt
smtpd_tls_CAfile = /etc/ssl/certs/mx.1ci.net.ca-bundle
----

[source,bash,linenums]
.Activate SMTPS port 465 in /etc/postfix/master.cf
----
smtps     inet  n       -       -       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_client_restrictions=$mua_client_restrictions
#  -o smtpd_reject_unlisted_recipient=no
#  -o smtpd_helo_restrictions=$mua_helo_restrictions
#  -o smtpd_sender_restrictions=$mua_sender_restrictions
#  -o smtpd_recipient_restrictions=
#  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
#  -o milter_macro_daemon_name=ORIGINATING
----

[source,bash,linenums]
.Add header for emails received via TLS
----
smtpd_tls_received_header = yes
----

[source,bash,linenums]
----
postfix reload
----

==== Relay for other users

(Microsoft Exchange)

Change the LDAP `query_filter` by adding a query against `(enabledService=relay_%d)`:

[source,bash,linenums]
.Installed /etc/postfix/ldap/sender_login_maps.cf
----
query_filter    = (&(objectClass=mailUser)(accountStatus=active)(enabledService=mail)(enabledService=smtp)(|(mail=%s)(&(enabledService=shadowaddress)(shadowAddress=%s))))
----

[source,bash,linenums]
.Modified /etc/postfix/ldap/sender_login_maps.cf
----
query_filter    = (&(objectClass=mailUser)(accountStatus=active)(enabledService=mail)(enabledService=smtp)(|(mail=%s)(&(enabledService=shadowaddress)(shadowAddress=%s))(enabledService=relay_%d)))
----

[cols="2",options="headers"]
.Users with `relay_` right:
|===
| User
| Relay for

| formmailer@medienhof.com
| wat-shop.de

| info@herwe.de
| cucubas.de, herwe.de, herwe.fr, herwetec.com

| info@mototherapie-muenster.de
| mototherapie-muenster.de

| deitmer@deitmer.de
| deitmer.de

| duesseldorf@bbors-kreuznacht.de
| bbors-kreuznacht.de

| meppen@bbors-kreuznacht.de
| bbors-kreuznacht.de

| mail@concunia-akademie.de
| concunia-akademie.de, concunia-steuer.de, concunia.de

| wbh@wbh-online.de
| wbh-online.de

| anja.meyer@egl-plan.de
| egl-plan.de

| kai.mueller@egl-plan.de
| egl-plan.de

| netmail.erlangen@egl-plan.de
| egl-plan.de

| netmail.landshut@egl-plan.de
| egl-plan.de

|===
